config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'users#index'
  resources :users

  resources :surveys

  resources :results
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :survey
  belongs_to :user
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :results
  has_many :users, :through => :results
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  has_many :results

  def generate_token
    hasher = Digest::SHA256.new
    self.token = hasher.hexdigest "#{ Time.new.strftime '%H %M %S %L %9N'} iashdlfkjhasdlkjhiuaweytr"
  end

  def generate_token!
    generate_token
    save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:survey_id, :user_id, :salary, :job_title)
    end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:company_name, :expires_at)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :token, :expires_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SalarySurvey</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/results/_form.html.haml
= form_for @result do |f|
  - if @result.errors.any?
    #error_explanation
      %h2= "#{pluralize(@result.errors.count, "error")} prohibited this result from being saved:"
      %ul
        - @result.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :survey_id
    = f.number_field :survey_id
  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :salary
    = f.number_field :salary
  .field
    = f.label :job_title
    = f.text_field :job_title
  .actions
    = f.submit 'Save'

app/views/results/edit.html.haml
%h1 Editing result

= render 'form'

= link_to 'Show', @result
\|
= link_to 'Back', results_path

app/views/results/index.html.haml
%h1 Listing results

%table
  %tr
    %th Survey
    %th User
    %th Salary
    %th Job title
    %th
    %th
    %th

  - @results.each do |result|
    %tr
      %td= result.survey_id
      %td= result.user_id
      %td= result.salary
      %td= result.job_title
      %td= link_to 'Show', result
      %td= link_to 'Edit', edit_result_path(result)
      %td= link_to 'Destroy', result, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Result', new_result_path

app/views/results/new.html.haml
%h1 New result

= render 'form'

= link_to 'Back', results_path

app/views/results/show.html.haml
%p#notice= notice

%p
  %b Survey:
  = @result.survey_id
%p
  %b User:
  = @result.user_id
%p
  %b Salary:
  = @result.salary
%p
  %b Job title:
  = @result.job_title

= link_to 'Edit', edit_result_path(@result)
\|
= link_to 'Back', results_path

app/views/surveys/_form.html.haml
= form_for @survey do |f|
  - if @survey.errors.any?
    #error_explanation
      %h2= "#{pluralize(@survey.errors.count, "error")} prohibited this survey from being saved:"
      %ul
        - @survey.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :company_name
    = f.text_field :company_name
  .field
    = f.label :expires_at
    = f.time_select :expires_at
  .actions
    = f.submit 'Save'

app/views/surveys/edit.html.haml
%h1 Editing survey

= render 'form'

= link_to 'Show', @survey
\|
= link_to 'Back', surveys_path

app/views/surveys/index.html.haml
%h1 Listing surveys

%table
  %tr
    %th Company name
    %th Expires at
    %th
    %th
    %th

  - @surveys.each do |survey|
    %tr
      %td= survey.company_name
      %td= survey.expires_at
      %td= link_to 'Show', survey
      %td= link_to 'Edit', edit_survey_path(survey)
      %td= link_to 'Destroy', survey, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Survey', new_survey_path

app/views/surveys/new.html.haml
%h1 New survey

= render 'form'

= link_to 'Back', surveys_path

app/views/surveys/show.html.haml
%p#notice= notice

%p
  %b Company name:
  = @survey.company_name
%p
  %b Expires at:
  = @survey.expires_at

= link_to 'Edit', edit_survey_path(@survey)
\|
= link_to 'Back', surveys_path

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :token
    = f.text_field :token
  .field
    = f.label :expires_at
    = f.time_select :expires_at
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Email
    %th Token
    %th Expires at
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.email
      %td= user.token
      %td= user.expires_at
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @user.email
%p
  %b Token:
  = @user.token
%p
  %b Expires at:
  = @user.expires_at

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path